services:
  deepstream:
    image: nvcr.io/nvidia/deepstream:6.4-samples-multiarch
    container_name: deepstream
    command: sleep infinity

  tao:
    image: nvcr.io/nvidia/tao/tao-toolkit:5.0.0-tf2.11.0
    container_name: tao
    command: sleep infinity